# Generated by Django 5.2.7 on 2025-10-05 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients_codi', '0002_alter_profile_height_alter_profile_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='alcohol',
            field=models.FloatField(default=0, help_text='알코올 (g)'),
        ),
        migrations.AddField(
            model_name='food',
            name='ash',
            field=models.FloatField(default=0, help_text='회분 (g)'),
        ),
        migrations.AddField(
            model_name='food',
            name='caffeine',
            field=models.FloatField(default=0, help_text='카페인 (mg)'),
        ),
        migrations.AddField(
            model_name='food',
            name='cholesterol',
            field=models.FloatField(default=0, help_text='콜레스테롤 (mg)'),
        ),
        migrations.AddField(
            model_name='food',
            name='choline',
            field=models.FloatField(default=0, help_text='콜린 (mg)'),
        ),
        migrations.AddField(
            model_name='food',
            name='copper',
            field=models.FloatField(default=0, help_text='구리 (mg)'),
        ),
        migrations.AddField(
            model_name='food',
            name='folate',
            field=models.FloatField(default=0, help_text='엽산 (μg)'),
        ),
        migrations.AddField(
            model_name='food',
            name='magnesium',
            field=models.FloatField(default=0, help_text='마그네슘 (mg)'),
        ),
        migrations.AddField(
            model_name='food',
            name='manganese',
            field=models.FloatField(default=0, help_text='망간 (mg)'),
        ),
        migrations.AddField(
            model_name='food',
            name='monounsaturated_fat',
            field=models.FloatField(default=0, help_text='단일불포화지방 (g)'),
        ),
        migrations.AddField(
            model_name='food',
            name='omega3',
            field=models.FloatField(default=0, help_text='오메가3 (g)'),
        ),
        migrations.AddField(
            model_name='food',
            name='omega6',
            field=models.FloatField(default=0, help_text='오메가6 (g)'),
        ),
        migrations.AddField(
            model_name='food',
            name='phosphorus',
            field=models.FloatField(default=0, help_text='인 (mg)'),
        ),
        migrations.AddField(
            model_name='food',
            name='polyunsaturated_fat',
            field=models.FloatField(default=0, help_text='다중불포화지방 (g)'),
        ),
        migrations.AddField(
            model_name='food',
            name='saturated_fat',
            field=models.FloatField(default=0, help_text='포화지방 (g)'),
        ),
        migrations.AddField(
            model_name='food',
            name='selenium',
            field=models.FloatField(default=0, help_text='셀레늄 (μg)'),
        ),
        migrations.AddField(
            model_name='food',
            name='trans_fat',
            field=models.FloatField(default=0, help_text='트랜스지방 (g)'),
        ),
        migrations.AddField(
            model_name='food',
            name='vitamin_b1',
            field=models.FloatField(default=0, help_text='비타민 B1 (mg)'),
        ),
        migrations.AddField(
            model_name='food',
            name='vitamin_b12',
            field=models.FloatField(default=0, help_text='비타민 B12 (μg)'),
        ),
        migrations.AddField(
            model_name='food',
            name='vitamin_b2',
            field=models.FloatField(default=0, help_text='비타민 B2 (mg)'),
        ),
        migrations.AddField(
            model_name='food',
            name='vitamin_b3',
            field=models.FloatField(default=0, help_text='비타민 B3 (mg)'),
        ),
        migrations.AddField(
            model_name='food',
            name='vitamin_b6',
            field=models.FloatField(default=0, help_text='비타민 B6 (mg)'),
        ),
        migrations.AddField(
            model_name='food',
            name='vitamin_e',
            field=models.FloatField(default=0, help_text='비타민 E (mg)'),
        ),
        migrations.AddField(
            model_name='food',
            name='vitamin_k',
            field=models.FloatField(default=0, help_text='비타민 K (μg)'),
        ),
        migrations.AddField(
            model_name='food',
            name='water',
            field=models.FloatField(default=0, help_text='수분 (g)'),
        ),
        migrations.AddField(
            model_name='food',
            name='zinc',
            field=models.FloatField(default=0, help_text='아연 (mg)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_alcohol',
            field=models.FloatField(default=0, help_text='총 알코올 (g)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_ash',
            field=models.FloatField(default=0, help_text='총 회분 (g)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_caffeine',
            field=models.FloatField(default=0, help_text='총 카페인 (mg)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_calcium',
            field=models.FloatField(default=0, help_text='총 칼슘 (mg)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_cholesterol',
            field=models.FloatField(default=0, help_text='총 콜레스테롤 (mg)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_choline',
            field=models.FloatField(default=0, help_text='총 콜린 (mg)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_copper',
            field=models.FloatField(default=0, help_text='총 구리 (mg)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_fiber',
            field=models.FloatField(default=0, help_text='총 식이섬유 (g)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_folate',
            field=models.FloatField(default=0, help_text='총 엽산 (μg)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_iron',
            field=models.FloatField(default=0, help_text='총 철분 (mg)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_magnesium',
            field=models.FloatField(default=0, help_text='총 마그네슘 (mg)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_manganese',
            field=models.FloatField(default=0, help_text='총 망간 (mg)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_monounsaturated_fat',
            field=models.FloatField(default=0, help_text='총 단일불포화지방 (g)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_omega3',
            field=models.FloatField(default=0, help_text='총 오메가3 (g)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_omega6',
            field=models.FloatField(default=0, help_text='총 오메가6 (g)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_phosphorus',
            field=models.FloatField(default=0, help_text='총 인 (mg)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_polyunsaturated_fat',
            field=models.FloatField(default=0, help_text='총 다중불포화지방 (g)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_potassium',
            field=models.FloatField(default=0, help_text='총 칼륨 (mg)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_saturated_fat',
            field=models.FloatField(default=0, help_text='총 포화지방 (g)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_selenium',
            field=models.FloatField(default=0, help_text='총 셀레늄 (μg)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_sodium',
            field=models.FloatField(default=0, help_text='총 나트륨 (mg)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_sugar',
            field=models.FloatField(default=0, help_text='총 당분 (g)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_trans_fat',
            field=models.FloatField(default=0, help_text='총 트랜스지방 (g)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_vitamin_a',
            field=models.FloatField(default=0, help_text='총 비타민 A (μg)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_vitamin_b1',
            field=models.FloatField(default=0, help_text='총 비타민 B1 (mg)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_vitamin_b12',
            field=models.FloatField(default=0, help_text='총 비타민 B12 (μg)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_vitamin_b2',
            field=models.FloatField(default=0, help_text='총 비타민 B2 (mg)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_vitamin_b3',
            field=models.FloatField(default=0, help_text='총 비타민 B3 (mg)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_vitamin_b6',
            field=models.FloatField(default=0, help_text='총 비타민 B6 (mg)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_vitamin_c',
            field=models.FloatField(default=0, help_text='총 비타민 C (mg)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_vitamin_d',
            field=models.FloatField(default=0, help_text='총 비타민 D (μg)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_vitamin_e',
            field=models.FloatField(default=0, help_text='총 비타민 E (mg)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_vitamin_k',
            field=models.FloatField(default=0, help_text='총 비타민 K (μg)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_water',
            field=models.FloatField(default=0, help_text='총 수분 (g)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_zinc',
            field=models.FloatField(default=0, help_text='총 아연 (mg)'),
        ),
    ]
