# Generated by Django 5.2.7 on 2025-10-05 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients_codi', '0003_food_alcohol_food_ash_food_caffeine_food_cholesterol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='beta_carotene',
            field=models.FloatField(default=0, help_text='베타카로틴 (μg)'),
        ),
        migrations.AddField(
            model_name='food',
            name='chlorine',
            field=models.FloatField(default=0, help_text='염소 (mg)'),
        ),
        migrations.AddField(
            model_name='food',
            name='chromium',
            field=models.FloatField(default=0, help_text='크롬 (μg)'),
        ),
        migrations.AddField(
            model_name='food',
            name='fluorine',
            field=models.FloatField(default=0, help_text='불소 (mg)'),
        ),
        migrations.AddField(
            model_name='food',
            name='iodine',
            field=models.FloatField(default=0, help_text='요오드 (μg)'),
        ),
        migrations.AddField(
            model_name='food',
            name='molybdenum',
            field=models.FloatField(default=0, help_text='몰리브덴 (μg)'),
        ),
        migrations.AddField(
            model_name='food',
            name='niacin',
            field=models.FloatField(default=0, help_text='나이아신 (mg)'),
        ),
        migrations.AddField(
            model_name='food',
            name='vitamin_d2',
            field=models.FloatField(default=0, help_text='비타민 D2 (μg)'),
        ),
        migrations.AddField(
            model_name='food',
            name='vitamin_d3',
            field=models.FloatField(default=0, help_text='비타민 D3 (μg)'),
        ),
        migrations.AddField(
            model_name='food',
            name='vitamin_k1',
            field=models.FloatField(default=0, help_text='비타민 K1 (μg)'),
        ),
        migrations.AddField(
            model_name='food',
            name='vitamin_k2',
            field=models.FloatField(default=0, help_text='비타민 K2 (μg)'),
        ),
    ]
