# Generated by Django 5.2.7 on 2025-10-05 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients_codi', '0004_food_beta_carotene_food_chlorine_food_chromium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='embedding',
            field=models.JSONField(blank=True, help_text='Gemini 임베딩 벡터', null=True),
        ),
    ]
