# Generated by Django 5.2.7 on 2025-10-05 05:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients_codi', '0005_food_embedding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['report_date'], name='nutrients_c_report__9e6c42_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['calorie_achievement'], name='nutrients_c_calorie_58385c_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['protein_achievement'], name='nutrients_c_protein_a74fad_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['carbs_achievement'], name='nutrients_c_carbs_a_93b8da_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['fat_achievement'], name='nutrients_c_fat_ach_b1affa_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['food_code'], name='nutrients_c_food_co_448bd9_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['source'], name='nutrients_c_source_7f0a64_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['name', 'category'], name='nutrients_c_name_593b4c_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['category', 'subcategory'], name='nutrients_c_categor_13db52_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['calories'], name='nutrients_c_calorie_30c60f_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['protein'], name='nutrients_c_protein_64355d_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['carbs'], name='nutrients_c_carbs_ed8908_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['fat'], name='nutrients_c_fat_197247_idx'),
        ),
        migrations.AddIndex(
            model_name='foodlog',
            index=models.Index(fields=['user', 'meal_type'], name='nutrients_c_user_id_f6cce5_idx'),
        ),
        migrations.AddIndex(
            model_name='foodlog',
            index=models.Index(fields=['user', 'consumed_date', 'meal_type'], name='nutrients_c_user_id_786881_idx'),
        ),
        migrations.AddIndex(
            model_name='foodlog',
            index=models.Index(fields=['food'], name='nutrients_c_food_id_8975bf_idx'),
        ),
        migrations.AddIndex(
            model_name='foodlog',
            index=models.Index(fields=['user', 'food'], name='nutrients_c_user_id_c70824_idx'),
        ),
        migrations.AddIndex(
            model_name='foodlog',
            index=models.Index(fields=['total_calories'], name='nutrients_c_total_c_71187a_idx'),
        ),
        migrations.AddIndex(
            model_name='foodlog',
            index=models.Index(fields=['total_protein'], name='nutrients_c_total_p_6f5651_idx'),
        ),
        migrations.AddIndex(
            model_name='foodlog',
            index=models.Index(fields=['total_carbs'], name='nutrients_c_total_c_70c445_idx'),
        ),
        migrations.AddIndex(
            model_name='foodlog',
            index=models.Index(fields=['total_fat'], name='nutrients_c_total_f_8f2252_idx'),
        ),
    ]
