# Generated by Django 5.2.7 on 2025-10-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients_codi', '0006_dailyreport_nutrients_c_report__9e6c42_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlog',
            name='total_beta_carotene',
            field=models.FloatField(default=0, help_text='총 베타카로틴 (μg)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_chlorine',
            field=models.FloatField(default=0, help_text='총 염소 (mg)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_chromium',
            field=models.FloatField(default=0, help_text='총 크롬 (μg)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_fluorine',
            field=models.FloatField(default=0, help_text='총 불소 (mg)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_iodine',
            field=models.FloatField(default=0, help_text='총 요오드 (μg)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_molybdenum',
            field=models.FloatField(default=0, help_text='총 몰리브덴 (μg)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_niacin',
            field=models.FloatField(default=0, help_text='총 나이아신 (mg)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_vitamin_d2',
            field=models.FloatField(default=0, help_text='총 비타민 D2 (μg)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_vitamin_d3',
            field=models.FloatField(default=0, help_text='총 비타민 D3 (μg)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_vitamin_k1',
            field=models.FloatField(default=0, help_text='총 비타민 K1 (μg)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='total_vitamin_k2',
            field=models.FloatField(default=0, help_text='총 비타민 K2 (μg)'),
        ),
    ]
