# Generated by Django 5.2.7 on 2025-10-05 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients_codi', '0007_foodlog_total_beta_carotene_foodlog_total_chlorine_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyReport',
        ),
    ]
