# Generated by Django 5.2.7 on 2025-10-09 02:26

import pgvector.django.vector
from django.db import migrations


def convert_jsonb_to_vector(apps, schema_editor):
    """JSON 임베딩을 vector 타입으로 변환"""
    with schema_editor.connection.cursor() as cursor:
        # 1. 임시 vector 컬럼 추가
        cursor.execute("""
            ALTER TABLE nutrients_codi_food 
            ADD COLUMN IF NOT EXISTS embedding_new vector(3072);
        """)
        
        # 2. JSON 배열을 vector로 변환하여 복사
        cursor.execute("""
            UPDATE nutrients_codi_food
            SET embedding_new = embedding::text::vector
            WHERE embedding IS NOT NULL;
        """)
        
        # 3. 기존 컬럼 삭제
        cursor.execute("""
            ALTER TABLE nutrients_codi_food 
            DROP COLUMN embedding;
        """)
        
        # 4. 새 컬럼 이름 변경
        cursor.execute("""
            ALTER TABLE nutrients_codi_food 
            RENAME COLUMN embedding_new TO embedding;
        """)


def convert_vector_to_jsonb(apps, schema_editor):
    """롤백: vector를 JSON으로 되돌림"""
    with schema_editor.connection.cursor() as cursor:
        # 1. 임시 JSONB 컬럼 추가
        cursor.execute("""
            ALTER TABLE nutrients_codi_food 
            ADD COLUMN IF NOT EXISTS embedding_new jsonb;
        """)
        
        # 2. vector를 JSON으로 변환
        cursor.execute("""
            UPDATE nutrients_codi_food
            SET embedding_new = embedding::text::jsonb
            WHERE embedding IS NOT NULL;
        """)
        
        # 3. 기존 컬럼 삭제
        cursor.execute("""
            ALTER TABLE nutrients_codi_food 
            DROP COLUMN embedding;
        """)
        
        # 4. 새 컬럼 이름 변경
        cursor.execute("""
            ALTER TABLE nutrients_codi_food 
            RENAME COLUMN embedding_new TO embedding;
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients_codi', '0009_install_pgvector'),
    ]

    operations = [
        migrations.RunPython(convert_jsonb_to_vector, convert_vector_to_jsonb),
    ]
