# Generated by Django 5.2.7 on 2025-10-09 04:18

import pgvector.django.vector
from django.db import migrations


def clear_old_embeddings(apps, schema_editor):
    """
    3072차원 임베딩을 NULL로 초기화
    (1536차원으로 재생성 예정)
    """
    Food = apps.get_model('nutrients_codi', 'Food')
    count = Food.objects.exclude(embedding__isnull=True).count()
    
    print(f'\n[INFO] {count:,}개의 기존 3072차원 임베딩을 삭제합니다...')
    print('[INFO] 마이그레이션 후 generate_embeddings 명령으로 1536차원으로 재생성하세요.')
    
    # 임베딩을 NULL로 설정
    Food.objects.update(embedding=None)
    
    print(f'[OK] 임베딩 초기화 완료! generate_embeddings로 재생성 필요.')


def restore_embeddings(apps, schema_editor):
    """롤백 시 - 수동으로 복원 필요"""
    print('[WARNING] 롤백 시 임베딩을 수동으로 재생성해야 합니다.')


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients_codi', '0010_alter_food_embedding'),
    ]

    operations = [
        # 먼저 기존 임베딩 초기화
        migrations.RunPython(clear_old_embeddings, restore_embeddings),
        
        # 그 다음 필드 변경
        migrations.AlterField(
            model_name='food',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
