# Generated by Django 5.2.7 on 2025-10-10 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients_codi', '0011_alter_food_embedding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='제목', max_length=200)),
                ('content', models.TextField(help_text='내용')),
                ('category', models.CharField(choices=[('tip', '식단 팁'), ('question', '질문'), ('review', '후기'), ('recipe', '레시피'), ('general', '자유게시판')], default='general', max_length=50)),
                ('views', models.IntegerField(default=0, help_text='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='nutrient_liked_posts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrient_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='댓글 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='nutrients_codi.communitycomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrient_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='nutrients_codi.communitypost')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['user', '-created_at'], name='nutrients_c_user_id_ce018f_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['category', '-created_at'], name='nutrients_c_categor_c30982_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['-views'], name='nutrients_c_views_081e34_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['-created_at'], name='nutrients_c_created_b2c52b_idx'),
        ),
        migrations.AddIndex(
            model_name='communitycomment',
            index=models.Index(fields=['post', 'created_at'], name='nutrients_c_post_id_8c199b_idx'),
        ),
        migrations.AddIndex(
            model_name='communitycomment',
            index=models.Index(fields=['user', '-created_at'], name='nutrients_c_user_id_fe3bb6_idx'),
        ),
    ]
