# Generated by Django 5.2.7 on 2025-10-09 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriterecipe',
            name='comment_count',
            field=models.IntegerField(default=0, verbose_name='댓글수'),
        ),
        migrations.AddField(
            model_name='favoriterecipe',
            name='comment_summary',
            field=models.TextField(blank=True, verbose_name='AI 댓글 요약'),
        ),
        migrations.AddField(
            model_name='favoriterecipe',
            name='description',
            field=models.TextField(blank=True, verbose_name='영상 설명'),
        ),
        migrations.AddField(
            model_name='favoriterecipe',
            name='difficulty_rating',
            field=models.IntegerField(default=0, verbose_name='난이도 평가 (1-5)'),
        ),
        migrations.AddField(
            model_name='favoriterecipe',
            name='negative_keywords',
            field=models.JSONField(blank=True, default=list, verbose_name='부정 키워드'),
        ),
        migrations.AddField(
            model_name='favoriterecipe',
            name='positive_keywords',
            field=models.JSONField(blank=True, default=list, verbose_name='긍정 키워드'),
        ),
        migrations.AddField(
            model_name='favoriterecipe',
            name='recipe_ingredients',
            field=models.TextField(blank=True, verbose_name='주요 재료'),
        ),
        migrations.AddField(
            model_name='favoriterecipe',
            name='recipe_steps',
            field=models.TextField(blank=True, verbose_name='요리 순서'),
        ),
        migrations.AddField(
            model_name='favoriterecipe',
            name='sentiment_rating',
            field=models.IntegerField(default=0, verbose_name='긍부정 평가 (1-5)'),
        ),
        migrations.AddField(
            model_name='favoriterecipe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='마지막 업데이트'),
        ),
        migrations.AddField(
            model_name='favoriterecipe',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='조회수'),
        ),
        migrations.AddIndex(
            model_name='favoriterecipe',
            index=models.Index(fields=['user', '-created_at'], name='recipe_ai_f_user_id_cae0ca_idx'),
        ),
    ]
