# Generated by Django 5.2.7 on 2025-10-10 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_ai', '0002_favoriterecipe_comment_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('category', models.CharField(choices=[('recipe', '레시피 공유'), ('question', '질문'), ('review', '요리 후기'), ('tip', '요리 팁'), ('general', '자유게시판')], default='general', max_length=50, verbose_name='카테고리')),
                ('views', models.IntegerField(default=0, verbose_name='조회수')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='YouTube 링크')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('likes', models.ManyToManyField(blank=True, related_name='recipe_liked_posts', to=settings.AUTH_USER_MODEL, verbose_name='좋아요')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '커뮤니티 게시글',
                'verbose_name_plural': '커뮤니티 게시글',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='댓글 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='recipe_ai.communitycomment', verbose_name='상위 댓글')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_comments', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='recipe_ai.communitypost', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '커뮤니티 댓글',
                'verbose_name_plural': '커뮤니티 댓글',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['user', '-created_at'], name='recipe_ai_c_user_id_f2abcc_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['category', '-created_at'], name='recipe_ai_c_categor_329d57_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['-views'], name='recipe_ai_c_views_69b7c7_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['-created_at'], name='recipe_ai_c_created_76d03a_idx'),
        ),
        migrations.AddIndex(
            model_name='communitycomment',
            index=models.Index(fields=['post', 'created_at'], name='recipe_ai_c_post_id_be153c_idx'),
        ),
        migrations.AddIndex(
            model_name='communitycomment',
            index=models.Index(fields=['user', '-created_at'], name='recipe_ai_c_user_id_843388_idx'),
        ),
    ]
